### ISSUE TITLE
Loss user context with SSR in production

### ISSUE THREAD

**Issue by jerryklimcik** [k2so-dev/laravel-nuxt#10]
Hi, first of all, thank you very much for your work, I appreciate it.

Unfortunately, when I log in and refresh the page, the cookie is removed and I lose the user context, so I'm like logged out. If I disable SSR everything works fine. This only happens in production, I can't replicate it locally. I've also noticed that this is a fairly common problem, but unfortunately I can't get past it.

I'm using Laravel Forge for deployment and I have two sites, backend (api.domain.com) and frontend (domain.com). I'm pretty sure there's some configuration issue but I can't find where it is. For some reason the Forge removes the `.env' content for the frontend, so I had to replace it with specific values. I'll get into why this is happening later. I'm not using Octane.

In `nuxt.config.ts` I have:
```
  runtimeConfig: {
    apiLocal: 'https://api.domain.com',
    public: {
      apiBase: 'https://api.domain.com',
      apiPrefix: '/api/v1',
      storageBase: 'https://api.domain.com/storage/',
      providers: {
        google: {
          name: "Google",
          icon: "",
          color: "gray",
        },
      },
    },
  },
```

And in `.env`:
```
APP_URL="https://api.domain.com"
API_LOCAL_URL=https://api.domain.com
FRONTEND_URL=https://domain.com
HOST=https://domain.com
PORT=443
SESSION_DOMAIN=.domain.com
```

Do you have any idea what might be causing this? 🙏

**Comment by jerryklimcik** [comment]
@k2so-dev I tried to use a private IP but I had no luck. The thing is, that the cookie is removed when I refresh the page, so there's no backend request. And I didn't find why a cookie is deleted and where :suspect:

**Comment by k2so-dev** [comment]
@jerryklimcik Make sure that in the `.env` file `AUTH_GUARD=api`
Make sure that in the `roles` table the `guard_name` column for roles has the value `api`. If this is not the case, then re-migrate or change the value in the table to `api`.

Try clearing the cache and re-caching with the commands:
```
php artisan optimize:clear
php artisan optimize
```

I don't know what else the problem could be. Unfortunately, I have no experience working with the Laravel Forge service.

**Comment by jerryklimcik** [comment]
Still nothing, I guess there will be a Forge setting so I'll try to find out. Anyway, thanks for your time, I close this thread 👍
