### ISSUE TITLE
Forge deployment

### ISSUE THREAD

**Issue by martin-ro** [k2so-dev/laravel-nuxt#2]
Hi,

thanks for this great starter package. I've been playing around with it locally.

Would you mind explaining how to deploy this setup with forge? As this is a monolith how'd you run octane and also serve the frontend with nuxt?

Cheers

**Comment by k2so-dev** [comment]
@martin-ro Hello. Unfortunately, I have no experience with laravel forge, but I can assume that it is necessary to create 2 proxy web servers separately for Laravel and for Nuxt.js. For example, Laravel on the api.example.com subdomain proxies 127.0.0.1:8000, and Nuxt on example.com proxies 127.0.0.1:3000.

I hope I somehow helped in solving the problem.

**Comment by martin-ro** [comment]
What tripped me up was that forge will hide the Octane & Horizon toggles when the path is set to `dist`. Other than that I think I got it mostly working. Thanks.

**Comment by LarryBarker** [comment]
@martin-ro Mind sharing details?
