### ISSUE TITLE
HTTPS Redirect

### ISSUE THREAD

**Issue by lucassmacedo** [k2so-dev/laravel-nuxt#4]
All my requests are going with https locally, is there any way to change this?

![image](https://github.com/k2so-dev/laravel-nuxt/assets/3357243/0c4bca09-f4a6-4bbc-9698-8c05d2155845)

**Comment by k2so-dev** [comment]
Hi. You need to make sure that the local address for the API_URL variable in the env file is used.

**Comment by lucassmacedo** [comment]
Yes, it's. 
![image](https://github.com/k2so-dev/laravel-nuxt/assets/3357243/385389a7-1087-4ec0-9bc0-511765ea3f17)

**Comment by lucassmacedo** [comment]
But it's http, not https.

**Comment by k2so-dev** [comment]
Another option is to check the browser setting "Upgrade connections to HTTPS".
You can also try disabling the `nuxt-security` module by deleting it from the `nuxt.config.ts` along with the `security` settings

**Comment by lucassmacedo** [comment]
I tried the two ways. But stays the same.
