### ISSUE TITLE
Is there any future plans about dockerizing this boilerplate?

### ISSUE THREAD

**Issue by crupko93** [k2so-dev/laravel-nuxt#5]
@k2so-dev Hi there!
Do you have future plans about dockerizing this boilerplate? 
Can you share some recommendations if I will want to do that by myself ?

**Comment by k2so-dev** [comment]
Hi, yes, I plan to add docker files, but I don't know exactly when I will be able to do it.
I recommend using the simplest solution - [Laravel Sail](https://laravel.com/docs/11.x/sail).

**Comment by crupko93** [comment]
Thank you for answering my questions

**Comment by nicholascourage** [comment]
@k2so-dev - I've developed a full Docker environment for this and would like to submit it as my first GitHub Contribution/PR to an opensource project like this - LaravelNuxt has been such an awesome resource! 

A full end-to-end Docker Environment to work with it locally has made it into something that I've learnt Nuxt with and will use for personal, professional and commercial projects too.

**Comment by crupko93** [comment]
Great job that would be awesome!!!

**Comment by k2so-dev** [comment]
@nicholascourage Hello, thanks for your interest in the project. But I would like to outline my point of view a little about the docker environment.

Full end-to-end Docker Environment as I see it can be a separate link to your repository inside "README.md" in the "Deploy" menu.

As for the docker files built into the current project, I am leaning towards the "Laravel Sail" approach, for which there is excellent documentation on the official website, many useful commands for managing project containers, the ability to add services via sail commands, etc.
Unfortunately, now it does not have several environment options, for example, for the production version it would be great to use Alpine containers, and for development standard containers from sail. Although this approach may seem over-engineered to some, so I’m not in a hurry with the Docker environment and it seems to me that it’s difficult to come up with something better than Laravel Sail.

**Comment by crupko93** [comment]
Yeah i would definitely look into that if you don’t mijd me asking to share
link of your version
