### ISSUE TITLE
Nuxt development environment is so slow

### ISSUE THREAD

**Issue by larsjanssen6** [k2so-dev/laravel-nuxt#6]
Hi,

Is it just me or is developing with nuxt extremely slow? When I hit save it takes 10 seconds every time before I even see it on my screen. When I re-run `npm run dev` it takes ages before the dev environment is ready.

**Comment by k2so-dev** [comment]
@larsjanssen6 Hello. I think this is true for everyone, especially if you enable DevTools and SSR mode in development mode. It depends on the resources of the hardware on which you run the development.
Sometimes it makes sense to disable DevTools and SSR if your work is focused on other things.

**Comment by mreduar** [comment]
> @larsjanssen6 Hello. I think this is true for everyone, especially if you enable DevTools and SSR mode in development mode. It depends on the resources of the hardware on which you run the development. Sometimes it makes sense to disable DevTools and SSR if your work is focused on other things.

I am having problems with enabling devtools with the project. I see that devtools is enabled by default in the configuration. But it does not appear anywhere. I have tried to install it manually but it still does not appear. Do you have any suggestions?

**Comment by k2so-dev** [comment]
> I see that devtools is enabled by default in the configuration.

Hi, devtools is disabled by default. Try changing "enabled" value to true.
https://github.com/k2so-dev/laravel-nuxt/blob/4a208987e31917eb2589854428a52bfce052953e/nuxt.config.ts#L15-L22

**Comment by mreduar** [comment]
> > I see that devtools is enabled by default in the configuration.
> 
> Hi, devtools is disabled by default. Try changing "enabled" value to true.
> 
> https://github.com/k2so-dev/laravel-nuxt/blob/4a208987e31917eb2589854428a52bfce052953e/nuxt.config.ts#L15-L22

You are right, I am very tired tonight and could not see that it was disabled by default. Thank you very much.
