### ISSUE TITLE
Redis not found

### ISSUE THREAD

**Issue by alniv94** [k2so-dev/laravel-nuxt#7]
Class redis not found when i run migrate.

![image](https://github.com/k2so-dev/laravel-nuxt/assets/89484751/51066cb0-d248-4c69-8696-0b02e9b45c33)

**Comment by alniv94** [comment]
Hello @k2so-dev 
i added the redis dll file in xammp and to php.ini
now i got this error
![image](https://github.com/k2so-dev/laravel-nuxt/assets/89484751/ea815471-92cb-4f1a-8bf8-a2d2c6d6b4b1)

i have no problem on redis in laravel 10.

**Comment by k2so-dev** [comment]
@alniv94 You can try clearing the cache:
`php artisan optimize:clear`
`php artisan optimize
`

Regenerate the ide helper code:
`php artisan ide-helper:generate`

**Comment by alniv94** [comment]
It still did not work, i tried to clone this in different machine still  got the same error.

**Comment by k2so-dev** [comment]
@alniv94 Try installing a fresh Laravel and enabling Redis as cache, queue and throttling with redis, then check if the problem persists.
