### ISSUE TITLE
How can we make a SSR call?

### ISSUE THREAD

**Issue by larsjanssen6** [k2so-dev/laravel-nuxt#9]
Hi,

How can we make a SSR call?

When i try this:

```
const { workspaces: workspaceData } = await $fetch<any>("workspaces");
```

It's always client side. When I add ssr:

```
const { workspaces: workspaceData } = await $fetch<any>("workspaces", {
       server: true
});
```

https://nuxt.com/docs/getting-started/data-fetching

It's not working , and still making a client side call (I have SSR enabled in my nuxt.config file). 

Thanks!

**Comment by k2so-dev** [comment]
Hi, you can see an example here https://github.com/k2so-dev/laravel-nuxt/blob/main/nuxt/app/pages/account/devices.vue

**Comment by danielbyte2** [comment]
> Hi, you can see an example here https://github.com/k2so-dev/laravel-nuxt/blob/main/nuxt/app/pages/account/devices.vue

@k2so-dev Are you sure that works? I can still see the API call being made in the browser networks tab
